name: Hello World Multiple Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  job1:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World from Job 1"

  job2:
    name: Welcome Job
    runs-on: ubuntu-latest
    steps:
      - name: Say Welcome
        run: echo "Welcome to GitHub Actions - Job 2"

  job3:
    name: Goodbye Job
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye from Job 3"
